runtime: python27
api_version: 1
threadsafe: true

skip_files:
  - .*\.json
  - .*\.md
  - .*\.pdf
  - .*\.sh
  - \.gitignore
  - Dockerfile
  - node_modules
  - scss
  - .git
  - Makefile
  - .dockerignore
  - .DS_Store
  - app.yaml

handlers:
- url: /
  static_files: MagneticParticleVisualization.html
  upload: MagneticParticleVisualization.html

- url: /css/(.*\.(css))$
  static_files: css/\1
  upload: css/.*\.(css)

- url: /js/(.*\.(js))$
  static_files: js/\1
  upload: js/.*\.(js)
